FROM docker:dind

# add docker repo
RUN apk update && \
    apk add make shunit2

# ADD source code and tests to the image
ENV PLUGIN_DIR /usr/local/plugin
ADD . ${PLUGIN_DIR}
ENV GOPATH ${PLUGIN_DIR}

WORKDIR ${PLUGIN_DIR}

ENTRYPOINT ["/bin/sh", "./test/plugin-test.entrypoint.sh"]
