PLUGIN_NAME = sixsq/img-authz-plugin-test
PLUGIN_TAG = latest

font := $(shell tput bold)$(shell tput setab 4)$(shell tput setaf 7)
sgr0 := $(shell tput sgr0)

.DEFAULT_GOAL: test
test: clean build run

clean:
	@echo "$(font) - [TEST] Removing previous test containers $(sgr0)"
	@docker rm -f sixsq-plugin-test || echo "Nothing to clean"

build:
	@echo "$(font) - [TEST] Building test Docker image $(sgr0)"
	@docker build -f Dockerfile.test -t ${PLUGIN_NAME}:test .

run:
	@echo "$(font) - [TEST] Starting test container $(sgr0)"
	@docker run --rm --privileged --name sixsq-plugin-test ${PLUGIN_NAME}:test "${PLUGIN_NAME}" "${PLUGIN_TAG}"